import assert from 'assert';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const testDir = dirname(fileURLToPath(import.meta.url));
const extensionDir = join(testDir, '..', 'iNaturalist Enhancement Suite');
const read = name => fs.readFileSync(join(extensionDir, name), 'utf8');

const observation = read('content-observation.js');
const domContext = read('domContext.js');
const similar = read('content-identify-similar.js');
const background = read('background.js');
const photos = read('content-photos-tab.js');
const scoreCrop = read('content-score-crop.js');
const similarCss = read('similar-species.css');
const options = read('options.js');
const autoPaging = observation.slice(
    observation.indexOf('function enableIdentifyAutoPaging'),
    observation.indexOf('function getIdentifyGridSignature')
);

console.log('Running Identify performance and lifecycle regression tests...');

assert.ok(observation.includes("window.addEventListener('scroll'"), 'Identify paging must use scroll events');
assert.ok(observation.includes('{ passive: true }'), 'Identify paging scroll listener must be passive');
assert.ok(autoPaging.includes("window.addEventListener('wheel', autoPagingWheelGuard"), 'Identify paging must guard wheel momentum during the page swap');
assert.ok(autoPaging.includes('event.preventDefault();'), 'Identify paging must prevent downward wheel momentum during the page swap');
assert.ok(autoPaging.includes('stopAutoPagingScrollGuard();'), 'Identify paging must remove the temporary wheel guard after the page swap');
assert.ok(autoPaging.includes("window.scrollTo({ top: 0, left: 0, behavior: 'auto' });"), 'Identify paging must return to the top after an automatic page replacement');
assert.ok(!autoPaging.includes('attributes: true'), 'Identify pagination observer must not watch every attribute mutation');
assert.ok(observation.includes("document.arrive('ul.ui-autocomplete.taxon-autocomplete'"), 'Taxon colorization must follow the current native autocomplete menu');

assert.ok(domContext.includes('inspectFetchResponse(response, requestUrl, options).catch'), 'Fetch inspection must be detached from the native response promise');
assert.ok(domContext.includes('const fetchPromise = oldFetch.call(window, url, options);'), 'Fetch interception must retain the native promise');
assert.ok(domContext.includes('return fetchPromise;'), 'The native fetch promise must be returned without an extension wrapper');
assert.ok(domContext.includes('inspectionResponse = response.clone();'), 'Fetch inspection must clone before the native page consumes the response');
assert.ok(domContext.includes('setTimeout(() => inspect(inspectionResponse), 0);'), 'Identify fetch inspection must yield to native modal rendering');
assert.ok(domContext.includes('const requestedObservationId = observationMatch[0].split(\'/\').pop();'), 'Stale observation responses must be rejected before JSON parsing');
assert.ok(domContext.includes('let activeTaxonSelection = null;'), 'Taxon selection must track one active request');
assert.ok(domContext.includes('selection.input?.isConnected'), 'Async taxon selection must reject a detached input');
assert.ok(domContext.includes('inatExtObservationChanging'), 'Observation navigation must cancel stale extension state');
assert.ok(domContext.includes("container.scrollIntoView({ block: 'center' });"), 'Quick ID must not animate scrolling during rapid review');
assert.ok(domContext.includes('String(observationId) === String(currentInterceptedObservationId)'), 'Placeholder guesses must match the current observation');
assert.ok(domContext.includes('function setPlaceholderComment(input, observationId, speciesGuess)'), 'Placeholder comment workflow must remain available');
assert.ok(domContext.includes('queuePlaceholderComment(input, selection?.observationId, selection?.speciesGuess);'), 'Programmatic taxon selections must write the placeholder comment');
assert.ok(domContext.includes('const value = `Placeholder: ${speciesGuess}`;'), 'Placeholder text must use the current species guess');
assert.ok(domContext.includes('setReactTextareaValue(textarea, value);'), 'Placeholder text must be written through React state');
assert.ok(domContext.includes("textarea.dispatchEvent(new Event('input', { bubbles: true }));"), 'Placeholder updates must notify the controlled React textarea through input');
assert.ok(domContext.includes('function queuePlaceholderComment(input, observationId, speciesGuess)'), 'Placeholder writes must retry after the comment form mounts');
assert.ok(domContext.includes('clearGeneratedPlaceholderComment();'), 'Navigation must clear extension-generated placeholder text before the next observation');
assert.ok(domContext.includes("String(currentInterceptedObservationId) !== String(observationId)"), 'A new observation response must also reset stale placeholder state');
assert.ok(domContext.includes("if (latestObservationId && String(latestObservationId) !== String(observationId)) return;"), 'Stale observation responses must not update Identify state');
assert.ok(!domContext.includes("setTimeout(() => {\n\t\ttextarea.dispatchEvent(new Event('blur'"), 'Comment blur must not be delayed across navigation');
assert.ok(domContext.includes("requestUrl && /^https:\\/\\/api\\.inaturalist\\.org\\/v\\d+\\/(?:observations\\/|computervision)"), 'Fetch inspection must ignore unrelated page requests');
assert.ok(domContext.includes('IDENTIFY_EMPTY_IMAGE_SRC'), 'Identify image requests must have a local placeholder available');
assert.ok(domContext.includes('shouldDeferIdentifyPhoto'), 'Identify image deferral must be scoped to photo sources and the Identify route');
assert.ok(domContext.includes('Element.prototype.setAttribute'), 'Identify image deferral must cover React attribute assignment');
assert.ok(domContext.includes('.taxon-image, .inat-quick-add-thumb'), 'Identify thumbnails must bypass gallery deferral');
assert.ok(domContext.includes(".image-gallery-thumbnail"), 'Identify gallery thumbnails must remain available as low-cost navigation cues');
assert.ok(observation.includes('restoreIdentifyThumbnails'), 'identified-taxon thumbnail restoration missing');
assert.ok(observation.includes('.image-gallery-thumbnail img[data-inat-fast-original-src]'), 'Identify gallery thumbnail restoration missing');
assert.ok(observation.includes('inat-identify-photo-count'), 'Identify popup must show the current image position and total count');
assert.ok(observation.includes('String.fromCharCode(0xf03e)'), 'Identify popup must render the image icon glyph rather than literal escape text');
assert.ok(observation.includes('span.photo-count::before'), 'Identify cards must show an image icon with the photo count');
assert.ok(observation.includes('min-width: 38px'), 'Identify card photo badges must leave room for the icon and count');
assert.ok(domContext.includes('markIdentifyNavigationPending'), 'Identify image deferral must begin before native navigation work');
assert.ok(domContext.includes('settleIdentifyNavigation'), 'Identify image deferral must release once the current observation is known');
assert.ok(observation.includes('enableIdentifyFastReview'), 'Identify fast-review mode must be configurable');
assert.ok(observation.includes("currentIdentifyObservationState = obs\n\t\t\t? (obs.taxon ? 'identified' : 'unknown')"), 'Identify review must distinguish identified and unknown observations');
assert.ok(observation.includes('function shouldShowQuickIdControls()'), 'Quick ID visibility must have an observation-state gate');
assert.ok(observation.includes("return currentIdentifyObservationState === 'unknown';"), 'Quick ID controls must only show for unknown Identify observations');
assert.ok(observation.includes('function clearQuickPlantPlaceholderDisplay()'), 'Quick ID placeholder display must have an explicit reset path');
assert.ok(observation.includes('clearQuickPlantPlaceholderDisplay();'), 'Quick ID placeholder must clear when the modal changes observations');
assert.ok(observation.includes('bufferedObservationFetchEvent'), 'Observation lifecycle must be buffered while settings load');
assert.ok(observation.includes('handleObservationFetch = event =>'), 'Observation lifecycle handler must be installed through the early relay');
assert.ok(observation.includes("document.addEventListener('observationFetch', event => {"), 'Observation lifecycle relay must be installed before settings load');
assert.ok(observation.includes('scheduleObservationStateFallback'), 'Observation state must have a direct modal fallback when the page event is missed');
assert.ok(observation.includes('inatObservationFallbackObserved'), 'Observation fallback must observe modal identity changes');
assert.ok(observation.includes('shouldShowQuickIdControls() ? \'grid\' : \'none\''), 'Quick ID controls must start hidden until an unknown observation is confirmed');
assert.ok(observation.includes("root.classList.toggle('inat-fast-identify-review'"), 'Fast review styling must be enabled only for pending or unknown observations');
assert.ok(observation.includes('if (!shouldDeferFastIdentifyEnhancements()) {'), 'Identified observations must restore the native visual path');
assert.ok(observation.includes('refreshIdentifyColorization();'), 'Identified observations must refresh CV visual enhancements');
assert.ok(observation.includes('if (score && !shouldDeferFastIdentifyEnhancements())'), 'CV hierarchy rows must remain available while heavy colour work is deferred');
assert.ok(observation.includes('const shouldShowMainCvHierarchy = () =>'), 'CV hierarchy visibility must have an observation-state gate');
assert.ok(observation.includes("if (currentIdentifyObservationState === 'unknown') return false;"), 'CV hierarchy rows must be hidden for unknown observations');
assert.ok(observation.includes('clearMainSuggestionHierarchies();'), 'CV hierarchy rows must be cleared during observation transitions');
assert.ok(observation.includes('computerVisionResults.delete(DEFAULT_KEY_NAME);'), 'CV results must not leak from the previous observation');
assert.ok(observation.includes('currentIdentifyObservationId = event.detail?.observationId || obs?.id || null;'), 'CV hierarchy work must track the active observation');
assert.ok(observation.includes('row.querySelector(\'.inat-main-cv-hierarchy\') !== hierarchy'), 'Late CV hierarchy responses must not populate a reused row');
assert.ok(observation.includes('Replay the lightweight row/hierarchy pass'), 'CV responses must replay hierarchy rows after the menu mounts');
assert.ok(observation.includes("image.loading = isActive ? 'eager' : 'lazy';"), 'Fast review must prioritize only the active modal image');
assert.ok(observation.includes("attributeFilter: ['class', 'aria-hidden', 'src', 'srcset']"), 'Fast review must follow active gallery slide and source changes');
assert.ok(observation.includes('EMPTY_IMAGE_SRC'), 'Fast review must use a local placeholder for inactive gallery images');
assert.ok(observation.includes('ORIGINAL_SRC_KEY'), 'Fast review must retain inactive gallery image sources');
assert.ok(observation.includes('restoreGalleryImage'), 'Fast review must restore an image source when its slide becomes active');
assert.ok(observation.includes('dataset.inatTaxonId'), 'CV classification trees must be replaced when the suggested taxon changes');
assert.ok(observation.includes('content-visibility: auto;'), 'Fast review must defer map paint work');
assert.ok(observation.includes('prefetchNextIdentifyPhoto'), 'Fast review must prefetch only the next Identify photo');
assert.ok(observation.includes("prefetchedImage.fetchPriority = 'low';"), 'Identify prefetch must yield to the active observation');
assert.ok(observation.includes('}, 500);'), 'Identify prefetch must wait for the current observation to settle');
assert.ok(observation.includes("label: 'Gastropods'"), 'Quick ID must include Gastropods');
assert.ok(observation.includes('id: 47114'), 'Gastropods Quick ID must use the iNaturalist Gastropoda taxon');
assert.ok(observation.includes("label: 'Nightshades'"), 'Quick ID must include Nightshades');
assert.ok(observation.includes('id: 48516'), 'Nightshades Quick ID must use the iNaturalist Solanaceae taxon');
assert.ok(observation.includes("label: 'Morning Glories'"), 'Quick ID must include Morning Glories');
assert.ok(observation.includes('id: 52346'), 'Ipomoea Quick ID must use the iNaturalist Ipomoea taxon');

assert.ok(similar.includes('new AbortController()'), 'Similar-species requests must be cancellable');
assert.ok(similar.includes('observationKey'), 'Similar-species rendering must deduplicate repeated observation events');
assert.ok(similar.includes('Promise.all(missingFromL1.map'), 'Taxon persistent-cache reads must run concurrently');
assert.ok(similar.includes('if (event.detail.cancelled) return;'), 'Similar-species selection must ignore navigation cancellation');
assert.ok(similar.includes("document.addEventListener('inatExtObservationChanging'"), 'Similar-species work must stop at navigation start');
assert.ok(similar.includes('function shouldDeferFastIdentifyExtras()'), 'Similar Species must defer only while Identify observations are pending or unknown');
assert.ok(similar.includes('function ensureSimilarSection('), 'Similar Species must be restorable for identified observations');
assert.ok(similar.includes('function removeSimilarSection()'), 'Similar Species must be removed during unknown-observation transitions');
assert.ok(similar.includes('async function loadSimilarSpecies({ includeSimilar = false } = {})'), 'Similar Species loading must support lazy classification and on-demand comparisons');
assert.ok(similar.includes('Load commonly confused species'), 'Commonly confused species must be available behind an explicit button');
assert.ok(similar.includes('Loading classification...'), 'Identify classification must load lazily after the observation is active');
assert.ok(!similar.includes('inat-load-classification-card-btn'), 'Identify classification must not add a manual load button');
assert.ok(similar.includes('loadSimilarSpecies({ includeSimilar: false })'), 'Classification must load without requesting confused species');
assert.ok(similar.includes('const classificationKey = `inat-classification-${compactTaxon.id}`'), 'Classification loading must use the persistent tree cache');
assert.ok(similar.includes('bufferedObservationFetchEvent'), 'Similar Species must not miss a cached observation during settings load');
assert.ok(similar.includes("document.addEventListener('observationFetch', event => {"), 'Similar Species lifecycle relay must be installed before settings load');
assert.ok(similar.includes('scheduleObservationRecovery'), 'Similar Species must recover when the page misses an observation event');
assert.ok(similar.includes('currentObservationId'), 'Similar Species must track the active modal observation independently of the panel DOM');
assert.ok(similar.includes('function syncSimilarSection()'), 'Similar Species must resync after the reused Identify modal renders');
assert.ok(similar.includes('schedulePanelSyncRetries'), 'Similar Species must retry after Identify rebuilds the reused Info panel');
assert.ok(similar.includes('[0, 100, 300, 600, 1200]'), 'Similar Species panel retries must be bounded');
assert.ok(similar.includes('function getLeadingTaxonFromModal(modal)'), 'Similar Species must use the rendered leading ID when the observation event lags');
assert.ok(similar.includes("/\\/taxa\\/\\d+(?:-|$)/"), 'Leading Identify cards must provide a numeric taxon fallback');
assert.ok(similar.includes("panel.dataset.inatObservationKey"), 'Similar Species panels must be scoped to the active observation');
assert.ok(similar.includes("panel.closest('.ObservationModal') === getCurrentModal()"), 'Late Similar Species responses must not populate a stale modal');
assert.ok(similar.includes("document.arrive('.ObservationModal', { existing: true }"), 'Similar Species must observe existing and newly created observation modals');
assert.ok(similarCss.includes('.inat-load-similar-btn'), 'The on-demand confused-species control must have extension styling');
assert.ok(domContext.includes('Content-script fallbacks may publish an observation event'), 'Placeholder context must accept fallback observation events');

assert.ok(!background.includes('getDetectorModel().catch(() => {})'), 'The detector must not warm eagerly in the background worker');
assert.ok(photos.includes('if (!storedDraftTaxon) syncDraftTaxonFromInput();'), 'Photos must not refetch a draft taxon already delivered by the page-world bridge');
assert.ok(photos.includes('if (!currentTabActive) return;'), 'Photos must not schedule taxon lookups while its tab is hidden');
assert.ok(similar.includes('enableIdentifyFastReview'), 'Similar Species fast-review setting must remain configurable');
assert.ok(background.includes('getDetectorModel'), 'Detector source remains covered by the existing lazy-start guard');
assert.ok(options.includes('identify-fast-review'), 'Fast Identify review must be exposed as an option');
assert.ok(options.includes('enableIdentifyFastReview'), 'Fast Identify review must persist its setting');
assert.ok(scoreCrop.includes("document.addEventListener('inatExtObservationChanging'"), 'Score/Crop work must stop at navigation start');
assert.ok(scoreCrop.includes("scoreButton.addEventListener('click'"), 'Score Image must remain click-activated');
assert.ok(scoreCrop.includes("cropButton.addEventListener('click'"), 'Crop for CV must remain click-activated');
assert.ok(!scoreCrop.includes("if (items.enableIdentifyFastReview !== false && window.location.pathname === '/observations/identify')"), 'Score/Crop controls must remain available during fast Identify review');
assert.ok(!photos.includes("if (settings.enableIdentifyFastReview !== false && window.location.pathname === '/observations/identify')"), 'Photos tab must remain available during fast Identify review');
assert.ok(photos.includes('if (currentTabActive) {\n\t\t\t\t\tloadPhotos();'), 'Photos requests must remain click-activated by the tab state');
assert.ok(options.includes('enableIdentifyAutoPaging'), 'Identify auto-paging must be configurable');

console.log('✅ Identify performance and lifecycle regression tests passed successfully!');
